Fix polyform libs names
purescript/registry-dev pull request #181
Opened 2021-06-08 13:14 UTC by paluh

2021-06-13 18:07 UTC, f-f requested changes

2021-06-13 18:07 UTC, f-f commented on new-packages.json
> +  "purescript-polyform-batteries-core": "https://github.com/purescript-polyform/batteries-core.git",
The other packages don't have a `bower.json` so they can be renamed - speaking of which, could you add a `bower.json` to them once we merge this change? - but `batteries-core` has one, so we should leave the existing entry in and add a new one instead.

```suggestion
  "purescript-batteries-core": "https://github.com/purescript-polyform/batteries-core.git",
  "purescript-polyform-batteries-core": "https://github.com/purescript-polyform/batteries-core.git",
```

2021-12-01 13:49 UTC, f-f commented
@paluh any update on this?

2021-12-03 12:04 UTC, paluh commented
@f-f sorry about this. I'm going to clean it up during the weekend.

2021-12-04 16:34 UTC, f-f commented
@paluh no worries! We're about to import all packages in the new Registry and it's going to be much harder to make such changes once we do that. So I wanted to make sure that we still need this change, and if that's the case that we merge it asap

2022-06-20 19:29 UTC, closed without merging