Records total number of packages and versions
purescript/registry-dev pull request #239
Opened 2021-09-22 20:37 UTC by mikesol

As per https://github.com/purescript/registry/issues/237.

I implemented this without an understanding of the underlying mechanics of the code, so it may be off. Also, it is an anti-pattern to pass the totals to the stats function only to be spit back out, but it was the quickest way from A to Z.

2021-09-22 20:40 UTC, thomashoneyman commented on ci/package.json
> +  "devDependencies": {
These are also made available via the nix shell

2021-09-30 16:50 UTC, thomashoneyman commented on ci/package.json
> +  "devDependencies": {
On second thought, I think we shouldn't add these to the package.json file because they are already included in the Nix shell, as well as other dependencies that can't be made available via NPM (namely `licensee` and `dhall-json`).

2021-09-30 19:41 UTC, mikesol commented on ci/package.json
> +  "devDependencies": {
Sounds good! I'll use nix-shell from here on out.

2021-10-05 18:23 UTC, f-f commented
I was wondering: why so many changes to the package-lock?

2021-10-05 20:29 UTC, thomashoneyman commented
> I was wondering: why so many changes to the package-lock?

It’s from the added dev dependencies — though I think we should remove them in favor of the Nix shell.

2021-10-06 08:51 UTC, thomashoneyman commented on ci/src/Registry/Scripts/BowerImport.purs
> +readRegistryFile :: FilePath -> Aff (Map RawPackageName PackageURL)
As a quick note -- before you go any further, you might want to merge with the default branch, because these functions have changed and you'll have conflicts.

2021-10-06 11:48 UTC, mikesol commented on ci/src/Registry/Scripts/BowerImport.purs
> +readRegistryFile :: FilePath -> Aff (Map RawPackageName PackageURL)
Just saw that, thanks for the heads up!

2021-10-06 12:12 UTC, mikesol commented
@thomashoneyman I've changed the scope of this PR to only getting rid of polymorphism in application code.

2021-10-06 12:25 UTC, mikesol commented
@thomashoneyman I think this is ready for review & potentially merge as-is given the reduced scope. With the monomorphic functions in there, the mapping you talk about is more clear from the types & it'll be easier to get cracking on the stats.

2021-10-06 15:31 UTC, thomashoneyman commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +  :: ProcessedPackages RawPackageName PackageURL
These were originally used in a couple places, which made it so that you couldn't have a concrete type for them. But if they're now this easy to specialize to specific types, then I wonder if we should just inline them in `LegacyImport.purs`? If they're not being reused at all then they don't really need to be in this file.

If you're interested, maybe that's something we could pair on or something I could do in a quick followup PR.

2021-10-06 15:34 UTC, thomashoneyman commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +type NameAndAddress = { address :: { owner :: String, repo :: String }, name :: RawPackageName }
```suggestion
type NameAndAddress = { address :: Address, name :: RawPackageName }
```

2021-10-06 15:34 UTC, thomashoneyman commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +type NameOriginalAndAddress = { address :: { owner :: String, repo :: String }, name :: PackageName, original :: RawPackageName }
```suggestion
type NameOriginalAndAddress = { address :: Address, name :: PackageName, original :: RawPackageName }
```

2021-10-06 15:38 UTC, thomashoneyman commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +type SemVerAndOriginal = { semVer :: SemVer, original :: RawVersion }
I sometimes find these highly-specific type synonym names a little harder to read than just seeing the record type directly, since they're just two or three fields; since they are only used in this file, what do you think of just inlining the types into the functions directly? For example:

```purs
forPackage
  :: ProcessedPackages RawPackageName PackageURL
  -> (RawPackageName -> PackageURL -> ExceptT ImportError Aff (Tuple { name :: RawPackageName, address :: Address } (Map RawVersion Unit))
  -> Aff (ProcessedPackages { name :: RawPackageName, address :: Address } (Map RawVersion Unit)
```

It makes the type signatures a bit long, but I still think they're reasonable to read and the functions are each only used in one place.

2021-10-06 15:40 UTC, thomashoneyman commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +  :: ProcessedPackages RawPackageName PackageURL
I understand that widens the scope of this PR way out, so I understand if you'd prefer to punt on that. I'm OK with making the types monomorphic since it compiles and just addressing my other feedback.

2021-10-06 16:37 UTC, mikesol commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +type SemVerAndOriginal = { semVer :: SemVer, original :: RawVersion }
Makes sense, totally doable

2021-10-06 16:37 UTC, mikesol commented on ci/src/Registry/Scripts/LegacyImport/Process.purs
> +  :: ProcessedPackages RawPackageName PackageURL
I'll do it now.

2021-10-06 16:50 UTC, mikesol commented
@thomashoneyman I've done an initial draft of inlining one function. It's not pretty, but it's all in one place. Lemme know if you'd like me to carve it up differently. Once I get feedback on that, I can keep going with the inlining. Another option is to go the other direction: carve out more stuff into `Process.purs` and keep `LegacyImport.purs` smaller.

2021-10-06 18:07 UTC, thomashoneyman commented
> @thomashoneyman I've done an initial draft of inlining one function. It's not pretty, but it's all in one place. Lemme know if you'd like me to carve it up differently. Once I get feedback on that, I can keep going with the inlining. Another option is to go the other direction: carve out more stuff into `Process.purs` and keep `LegacyImport.purs` smaller.

Yea, I think this is too much to try and put into this PR. Sorry for the dead end! Let's revert https://github.com/purescript/registry/pull/239/commits/cce789a7d7dbefaf35b6033a22508ff472f82276 and just inline the type synonyms into the `for*` functions and call it there, and I can merge this.

2021-10-06 18:08 UTC, thomashoneyman commented on ci/src/Registry/Scripts/LegacyImport.purs
> +type Address = { owner :: String, repo :: String }
This already exists in the `Foreign.GitHub` module, so you should be able to just reuse that.

2021-10-06 18:45 UTC, mikesol commented
> That way I can go ahead and merge this PR.

Done! No worries for the back-and-forth on refactorings, they're all minor and it's tough to know what works until we try it out.

2021-10-06 19:03 UTC, thomashoneyman commented
I'm personally OK with the long line lengths that were there before https://github.com/purescript/registry/pull/239/commits/710b4852b959192fee419f10cf0af1357a8e591a, and find it a bit easier to read than the line breaks. I know I'm deep into "this is my opinion" territory here, and perhaps you and @f-f feel differently.

2021-10-06 19:03 UTC, thomashoneyman commented
That said, I'm going to go ahead and 👍 and see if @f-f has anything to add. I think we'll probably want to tweak this more going forward, but it's not necessary to have the back-and-forth go on for too long.

2021-10-06 19:04 UTC, thomashoneyman submitted a review, later dismissed

2021-10-07 07:23 UTC, mikesol commented
@thomashoneyman @f-f I added the `stats` stuff to this PR just cuz I have time now & won't necessarily in a bit. The monomorphic stuff made it super easy to write as I just let the compiler guide me until I got the types right for the new fields in `Stats`. I think this corresponds to the spec you wanted, Thomas, but if not lemme know & I'll tweak it!

2021-10-07 09:02 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +  mockLicense = unsafeCoerce "None"
I'd rather not use `unsafeCoerce` here because it admits so many types -- for example, if we change `License` to not just be a simple string internally then this will silently break.

Instead, we should use the provided constructor functions for these various newtypes -- ie. `License.parse` or `PackageName.parse` or `SemVer.parseSemVer`. Then, depending on whether they return a `Maybe` or an `Either` we can unwrap them with either:

```purs
-- on `Maybe` values
unsafePartial $ Maybe.fromJust ...

-- on `Either` values
Either.fromRight' (\_-> unsafeCrashWith "Unexpected Left") ...
```

That way we get a compiler error if the constructor function for these newtypes changes to accept a different type.

2021-10-07 09:07 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +  mockSemVer = unsafeCoerce "0.0.0"
This isn't correct -- a `SemVer` isn't just the raw string itself, it's a bigger structure:

https://github.com/purescript/registry/blob/b1f4b5e0052ab1f9c01c081e0d83a9f2ec6f92a7/ci/src/Foreign/SemVer.purs#L21-L30

You'll want to use `SemVer.parseSemVer` here:

https://github.com/purescript/registry/blob/b1f4b5e0052ab1f9c01c081e0d83a9f2ec6f92a7/ci/src/Foreign/SemVer.purs#L60-L61

and do the same thing described in:
https://github.com/purescript/registry/pull/239/files?authenticity_token=kII5YqA1fsfSTJ1yXpArH55gg%2BZIzDd88oD4dZcJNiE%2F0c4e8aXNAR5cj%2FjeUVksJWVRQqnPrtyD6WR9PVmcRw%3D%3D&file-filters%5B%5D=.purs#r723988926

2021-10-07 09:08 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +        $ Map.toUnfoldable examplePackageResults.packages
```suggestion
        $ (Map.toUnfoldable examplePackageResults.packages :: _ -> Array _)
```

2021-10-07 09:15 UTC, mikesol commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +  mockSemVer = unsafeCoerce "0.0.0"
One thing to check out is https://github.com/purescript/registry/issues/246. I think there may be an issue with the FFI here (I could be wrong). When I tried using the type suggested by the constructor, it crashed in the Js layer.

2021-10-07 09:17 UTC, mikesol commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +  mockLicense = unsafeCoerce "None"
Totally makes sense. Would you be open to exporting a function ie `unsafePackageName` for the constructor in the file itself. The danger with this stuff is that people will wind up using it, which defeats the purpose of not exporting the constructor, but usually stuff that starts with `unsafe` is known to be use-at-your-own-risk.

2021-10-07 09:23 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +  mockSemVer = unsafeCoerce "0.0.0"
If you weren't using `parseSemVer` then I think you would fail the `instanceof` check in the JS layer

2021-10-07 09:25 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +  mockLicense = unsafeCoerce "None"
I'd rather just use the `unsafe` in the places where we really need to use it, and not export an unsafe constructor; we should only really be using unsafe things in the test code and I don't mind the extra verbosity there.

2021-10-07 09:26 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +        $ (Map.toUnfoldable examplePackageResults.packages :: _ -> Array _)
Whoops, must have missed a paren. Maybe this?

```purs
$ ((Map.toUnfoldable examplePackageResults.packages) :: _ -> Array _))
```

2021-10-07 10:12 UTC, mikesol commented
@thomashoneyman I incorporated your suggestions - everything should be in there now.

2021-10-08 10:24 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +              <> " failed)"
This still results in output I find a little difficult to parse (pasted at the bottom of this comment). Specifically, it's not clear what packages fully succeeded (no versions dropped), partially succeeded (some versions dropped), or fully failed (all versions dropped). Could we try adjusting to:

```
Packages: 1575 total (1175 succeeded, 200 partially succeeded, 200 failed)
Versions: 10,000 total (8,000 succeeded, 2,000 failed)
```

as the top line?

2021-10-08 10:24 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +              <> " failed)"
Current output on this PR from running `spago run -m Registry.Scripts.LegacyImport':

```
Packages: 1575 total (1200 with successes, 127 with failures)
Versions: 774 total (486 successful, 76 failed)
Failures by error:
  manifestError: 1215 occurrences (314 packages / 1215 versions)
    badLicense: 481 occurrences (76 packages / 481 versions)
    missingLicense: 452 occurrences (141 packages / 452 versions)
    badDependencyVersions: 307 occurrences (114 packages / 307 versions)
    badVersion: 50 occurrences (34 packages / 50 versions)
  noDependencyFiles: 66 occurrences (34 packages / 66 versions)
  resourceError: 32 occurrences (32 packages / 0 versions)
  malformedPackageName: 1 occurrences (1 packages / 1 versions)

2021-10-08 10:27 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
> +              <> " failed)"
While you're here, could we replace the

```
X occurrences (X packages / X versions)
```

lines with the below instead, since occurrences == versions?

```
X versions across X packages
```

(or another format of your choice -- we just don't need to duplicate occurrences / versions since they're the same)

2021-10-08 10:30 UTC, thomashoneyman commented
@mikesol Just a couple quick comments about the output format and then we can get this in. Thanks!

2021-10-08 10:43 UTC, f-f approved these changes
This looks good, thanks @mikesol! I think this is good to go once we address Thomas' suggestions

2021-10-08 11:50 UTC, mikesol commented
@thomashoneyman Done :+1:

2021-10-08 12:16 UTC, thomashoneyman commented
@mikesol — in this output, what is the difference between “partially failed” and “partially succeeded”? Shouldn’t they be the same thing?

I think we still need to bucket the successes / failures according to the three criteria set out in https://github.com/purescript/registry/pull/239#discussion_r724891862

For example, this test output:

```
Packages: 7 total (2 totally succeeded, 2 partially succeeded, 5 totally failed, 5 partially failed)
Versions: 8 total (2 totally succeeded, 5 partially succeeded, 4 totally failed, 7 partially failed)
```

...doesn't really make sense:

* If there are 7 packages, then succeeded + partially succeeded + failed should add up to 7, but this adds up to 14.
* Packages can "partially succeed" if some versions in the package parsed, but other versions didn't. But while there are four categories represented in this output, there are really only three possible categories: "fully succeeded" (no versions failed), "partially succeeded" (some, but not all, versions failed), or "failed" (all versions failed).
* Versions can't "partially succeed"; a version either parses or doesn't. So versions should only have "succeeded" and "failed" categories.

2021-10-08 14:21 UTC, thomashoneyman commented on ci/test/Registry/Scripts/BowerImport/Stats.purs
>  import Registry.Prelude
I'm not totally sure what's going on here, but it looks like the directory for this is incorrect (it should be `ci/test/Registry/Scripts/LegacyImport/Stats.purs`). Can we rename it?

2021-10-08 14:27 UTC, thomashoneyman requested changes
I think a few things need to be fixed about this, as per my latest comments

2021-10-11 09:49 UTC, mikesol commented
> I think a few things need to be fixed about this, as per my latest comments

Done & ready for another review.

2021-10-11 11:21 UTC, thomashoneyman commented
The output looks better:

```
Packages: 1575 total (1200 totally succeeded, 248 partially succeeded, 127 totally failed)
Versions: 11521 total (10239 totally succeeded, 0 partially succeeded, 1282 totally failed)
Failures by error:
  manifestError: 1215 versions across 314 packages
    badLicense: 481 versions across 76 packages
    missingLicense: 452 versions across 141 packages
    badDependencyVersions: 307 versions across 114 packages
    badVersion: 50 versions across 34 packages
  noDependencyFiles: 66 versions across 34 packages
  resourceError: 0 versions across 32 packages
  malformedPackageName: 1 versions across 1 packages
```

2021-10-11 11:28 UTC, thomashoneyman approved these changes

2021-10-11 11:28 UTC, merged