Add package: parsing-expect (#56)
purescript/registry-dev pull request #56
Opened 2020-08-24 17:20 UTC by markfarrell

https://github.com/purescript/package-sets/pull/665

2020-08-24 17:26 UTC, thomashoneyman requested changes

2020-08-24 17:26 UTC, thomashoneyman commented on new-packages.json
> +  "purescript-parsing-expect": "https://github.com/markfarrell/purescript-parsing-expect.git"
Missing a comma at the end of the previous line (after mol-draw) so this json is invalid at the moment

2020-08-25 18:08 UTC, markfarrell commented on new-packages.json
> +  "purescript-parsing-expect": "https://github.com/markfarrell/purescript-parsing-expect.git"
Sorry will fix

2020-08-26 04:36 UTC, markfarrell commented on new-packages.json
> +  "purescript-parsing-expect": "https://github.com/markfarrell/purescript-parsing-expect.git"
Added comma at the end of the previous line. Good now?

2020-08-26 06:54 UTC, thomashoneyman approved these changes

2020-08-26 06:54 UTC, thomashoneyman commented
I don't have the ability to merge, but this looks good now.

2020-08-26 08:57 UTC, merged